version: “3.9”
services:
  proxy:
    container_name: laravel-react-proxy
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html

  app:
    container_name: laravel-react-app
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/php/php.ini
      - ./src:/var/www/html
    ports:
      - "5173:5173"

  db:
    container_name: laravel-react-db
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - laravel-react-db-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
volumes:
  laravel-react-db-volume: